### ISSUE TITLE
关于Adobe Song Std字体的问题

### ISSUE THREAD

**Issue by adaxidedakaonang** [mnjey/XDUthesisBachelor#5]
作者你好，我下载字体的时候发现只有Adobe Song Std L这种字体，所以我把你代码里的Adobe字体都注释掉了。关于latex我接触的不多，我把你的字体改成L之后提示找不到这个字体，顺便也问问有没有遇到类似问题的同学，Mac环境
%\setCJKmainfont{Adobe Song Std}
%\setCJKsansfont{Adobe Heiti Std}
%\setCJKfamilyfont{song}{Adobe Song Std}
%\setCJKfamilyfont{hei}{Adobe Heiti Std}
就这几个字体

**Comment by mnjey** [comment]
人在外面，等晚上回学校我给你传一下字体吧，留个邮箱

**Comment by adaxidedakaonang** [comment]
403636538@qq.com谢谢啦！

**Comment by adaxidedakaonang** [comment]
问题找到了，我只导入了字体但是没有激活，激活后一切正常。
